apiVersion: v1
kind: Service
metadata:
  name: predict-backend
  namespace: predict
spec:
  selector:
    app: predict-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
