apiVersion: v1
kind: Service
metadata:
  name: predict-frontend
  namespace: predict
spec:
  selector:
    app: predict-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
