import type { Signal } from '@pmt/shared'

export const mockSignals: Signal[] = [
  {
    id: 'sig-001',
    analyzer: 'llm_prob',
    marketId: 'poly-fed-rate-cut-june',
    marketTitle: 'Fed Rate Cut by June 2026',
    timestamp: new Date(Date.now() - 3 * 60000).toISOString(),
    signalType: 'edge',
    confidence: 0.85,
    direction: 'buy_yes',
    metadata: {
      fairValue: 0.78,
      edgePct: 9.9,
      currentPrice: 0.71,
      reasoning: 'Recent CPI data shows continued disinflation. Fed dot plot suggests 2 cuts in 2026. Market underpricing probability of June cut.',
    },
  },
  {
    id: 'sig-002',
    analyzer: 'arb',
    marketId: 'kalshi-sp500-6000',
    marketTitle: 'S&P 500 Above 6,000 EOY',
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    signalType: 'arb_opportunity',
    confidence: 0.92,
    direction: 'buy_yes',
    metadata: {
      fairValue: 0.70,
      edgePct: 11.1,
      currentPrice: 0.63,
      reasoning: 'Polymarket prices same event at 0.67 vs Kalshi 0.63. Cross-platform spread = 4.0%.',
    },
  },
  {
    id: 'sig-003',
    analyzer: 'sentiment',
    marketId: 'poly-btc-100k-q2',
    marketTitle: 'Bitcoin Above $100K Q2 2026',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    signalType: 'sentiment_shift',
    confidence: 0.68,
    direction: 'buy_no',
    metadata: {
      edgePct: -6.7,
      currentPrice: 0.45,
      reasoning: 'Social sentiment turned bearish after SEC delay on ETF expansion. Twitter sentiment score dropped from +0.3 to -0.15 in 4h.',
    },
  },
  {
    id: 'sig-004',
    analyzer: 'llm_prob',
    marketId: 'poly-us-election-2028',
    marketTitle: 'US Election 2028 - Republican Win',
    timestamp: new Date(Date.now() - 22 * 60000).toISOString(),
    signalType: 'edge',
    confidence: 0.72,
    direction: 'buy_no',
    metadata: {
      fairValue: 0.48,
      edgePct: -7.7,
      currentPrice: 0.52,
      reasoning: 'Polling data shows incumbent party advantage. Historical models suggest 52% is overpriced for a race this far out.',
    },
  },
  {
    id: 'sig-005',
    analyzer: 'llm_prob',
    marketId: 'kalshi-recession-2026',
    marketTitle: 'US Recession in 2026',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    signalType: 'edge',
    confidence: 0.78,
    direction: 'buy_no',
    metadata: {
      fairValue: 0.22,
      edgePct: -21.4,
      currentPrice: 0.28,
      reasoning: 'Leading indicators (yield curve, PMI, employment) all positive. Market overpricing recession risk.',
    },
  },
]
